from pathlib import Path
p=Path('/home/ubuntu/nox-offline-player/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('import { useEffect as useDocumentEffect } from "react";', 'import { useEffect as useDocumentEffect } from "react";\nimport { trpc } from "@/lib/trpc";')
s=s.replace('type MediaItem = { id: string; file: File; url: string; kind: "audio" | "video" };', '''type MediaItem = { id: string; file: File; url: string; kind: "audio" | "video" };\ntype StoredMedia = { id: number; originalName: string; mimeType: string; size: number; storageUrl: string; createdAt: Date };''')
s=s.replace('  const [transcribing, setTranscribing] = useState(false);', '''  const [transcribing, setTranscribing] = useState(false);\n  const [uploadingName, setUploadingName] = useState<string | null>(null);\n  const storedFilesQuery = trpc.files.list.useQuery(undefined, { enabled: isAuthenticated, retry: false });\n  const deleteStoredFile = trpc.files.delete.useMutation({\n    onSuccess: () => void storedFilesQuery.refetch(),\n  });''')
needle='''  const addMedia = useCallback((files: File[]) => {'''
insert='''  const uploadToLibrary = useCallback(async (file: File) => {\n    if (!isAuthenticated) {\n      setNotice("請先登入，才能保存至媒體庫");\n      return;\n    }\n    setUploadingName(file.name);\n    try {\n      const response = await fetch("/api/files/upload", {\n        method: "POST",\n        credentials: "include",\n        headers: {\n          "Content-Type": file.type || "application/octet-stream",\n          "X-File-Name": encodeURIComponent(file.name),\n          "X-File-Type": file.type || "application/octet-stream",\n        },\n        body: file,\n      });\n      if (!response.ok) {\n        const payload = await response.json().catch(() => ({}));\n        throw new Error(payload.message || "上傳失敗");\n      }\n      await storedFilesQuery.refetch();\n      setNotice(`「${file.name}」已保存至你的媒體庫`);\n    } catch (error) {\n      setNotice(error instanceof Error ? error.message : "檔案上傳失敗");\n    } finally {\n      setUploadingName(null);\n    }\n  }, [isAuthenticated, storedFilesQuery]);\n\n'''+needle
if needle not in s: raise SystemExit('addMedia needle missing')
s=s.replace(needle,insert)
# bottom privacy copy and controls
s=s.replace('<span>資料不離開裝置</span>', '<span>本機播放不自動上傳</span>')
s=s.replace('<button onClick={() => subtitleInput.current?.click()} className="secondary-button"><Subtitles size={15} /> 載入字幕</button>', '<button onClick={() => subtitleInput.current?.click()} className="secondary-button"><Subtitles size={15} /> 載入字幕</button><button onClick={() => current && void uploadToLibrary(current.file)} disabled={!current || !!uploadingName} className="secondary-button disabled:opacity-50"><FolderOpen size={15} /> {uploadingName ? "保存中…" : "保存至媒體庫"}</button>')
# both PanelContent invocations
old='''PanelContent panel={panel} items={items} currentId={currentId} cues={cues} activeCue={activeCue} captionSize={captionSize} captionOffset={captionOffset} setCaptionSize={setCaptionSize} setCaptionOffset={setCaptionOffset} selectItem={selectItem} removeItem={removeItem} onClose={() => setPanel(null)} onLoad={() => subtitleInput.current?.click()} />'''
new='''PanelContent panel={panel} items={items} currentId={currentId} cues={cues} activeCue={activeCue} captionSize={captionSize} captionOffset={captionOffset} setCaptionSize={setCaptionSize} setCaptionOffset={setCaptionOffset} selectItem={selectItem} removeItem={removeItem} onClose={() => setPanel(null)} onLoad={() => subtitleInput.current?.click()} storedFiles={(storedFilesQuery.data ?? []) as StoredMedia[]} onUpload={uploadToLibrary} uploadingName={uploadingName} onDeleteStored={(id) => deleteStoredFile.mutate({ id })} />'''
if s.count(old)!=2: raise SystemExit(f'Panel invocations found {s.count(old)}')
s=s.replace(old,new)
# intro copy update
s=s.replace('拖放檔案後，瀏覽器會建立暫時的本機網址；原始媒體不需要離開這台裝置。', '拖放檔案後，瀏覽器會建立暫時的本機網址；原始媒體不會自動離開這台裝置。需要跨裝置使用時，再手動保存到你的私人媒體庫。')
# replace signature and queue section with a less invasive insertion after queue content
old_sig='''function PanelContent({ panel, items, currentId, cues, activeCue, captionSize, captionOffset, setCaptionSize, setCaptionOffset, selectItem, removeItem, onClose, onLoad }: { panel: Panel; items: MediaItem[]; currentId: string | null; cues: Cue[]; activeCue: Cue | null; captionSize: number; captionOffset: number; setCaptionSize: (value: number) => void; setCaptionOffset: (value: number) => void; selectItem: (item: MediaItem) => void; removeItem: (id: string) => void; onClose: () => void; onLoad: () => void }) {'''
new_sig='''function PanelContent({ panel, items, currentId, cues, activeCue, captionSize, captionOffset, setCaptionSize, setCaptionOffset, selectItem, removeItem, onClose, onLoad, storedFiles, onUpload, uploadingName, onDeleteStored }: { panel: Panel; items: MediaItem[]; currentId: string | null; cues: Cue[]; activeCue: Cue | null; captionSize: number; captionOffset: number; setCaptionSize: (value: number) => void; setCaptionOffset: (value: number) => void; selectItem: (item: MediaItem) => void; removeItem: (id: string) => void; onClose: () => void; onLoad: () => void; storedFiles: StoredMedia[]; onUpload: (file: File) => void; uploadingName: string | null; onDeleteStored: (id: number) => void }) {'''
if old_sig not in s: raise SystemExit('signature missing')
s=s.replace(old_sig,new_sig)
# Inject cloud library before queue closing panel div. Unique sequence ends after queue item map then </div>}
needle='''</div>}</div>}{panel === "captions"'''
replacement='''</div>}<div className="mt-6 border-t border-white/[0.08] pt-5"><div className="mb-3 flex items-center justify-between"><p className="eyebrow">私人媒體庫</p><span className="text-[10px] text-white/30">{storedFiles.length} 個檔案</span></div>{storedFiles.length === 0 ? <p className="text-[11px] leading-5 text-white/35">尚未保存檔案。播放器下方的「保存至媒體庫」只會在你明確操作後上傳。</p> : <div className="space-y-2">{storedFiles.map((file) => <div key={file.id} className="flex items-center gap-2 rounded-xl bg-white/[0.03] p-3"><FileAudio size={15} className="shrink-0 text-[#c9ff65]" /><span className="min-w-0 flex-1"><span className="block truncate text-xs text-white/70">{file.originalName}</span><span className="mt-1 block text-[10px] text-white/30">{formatBytes(file.size)} · {new Date(file.createdAt).toLocaleDateString()}</span></span><a href={file.storageUrl} target="_blank" rel="noreferrer" className="text-[10px] text-[#c9ff65] hover:text-white">開啟</a><button onClick={() => onDeleteStored(file.id)} className="p-1 text-white/25 hover:text-red-300" aria-label={`刪除 ${file.originalName}`}><X size={13} /></button></div>)}</div>}</div></div>}{panel === "captions"'''
if needle not in s: raise SystemExit('queue insertion needle missing')
s=s.replace(needle,replacement)
# use onUpload currently not used; add a per queue button after item metadata? avoid unused via small note upload button on each item not needed. Actually onUpload/ uploadingName unused TS noUnused? likely no. Use cloud title action simple in queue header.
s=s.replace('<p className="eyebrow">私人媒體庫</p>', '<p className="eyebrow">私人媒體庫</p>')
# Add formatBytes helper before SettingRow
s=s.replace('function SettingRow(', '''function formatBytes(bytes: number) {\n  if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`;\n  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;\n}\n\nfunction SettingRow(''')
# use props to prevent no-unused by add action in empty/list header not necessary but onUpload should enable saving from queue
s=s.replace('<div className="mb-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed', '<button onClick={() => items.find((item) => item.id === currentId) && onUpload(items.find((item) => item.id === currentId)!.file)} disabled={!currentId || !!uploadingName} className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#c9ff65]/20 bg-[#c9ff65]/[0.05] py-3 text-xs text-[#c9ff65] disabled:opacity-40">保存目前檔案至媒體庫</button><button onClick={() => document.querySelector<HTMLInputElement>(\'input[type="file"]\')?.click()} className="mb-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed')
p.write_text(s)
