export type ModelTask = "stt" | "mt";

export type LocalModel = {
  id: string;
  hf: string;
  name: string;
  nameZh: string;
  task: ModelTask;
  sizeLabel: string;
  quality: "fast" | "balanced" | "accurate";
  langs: string;
  langsZh: string;
  note?: string;
  src?: string;
  tgt?: string;
};

export const LANGUAGES: { id: string; label: string; whisper?: string }[] = [
  { id: "auto", label: "Auto / 自動", whisper: undefined },
  { id: "zh", label: "中文", whisper: "chinese" },
  { id: "en", label: "English", whisper: "english" },
  { id: "ja", label: "日本語", whisper: "japanese" },
  { id: "ko", label: "한국어", whisper: "korean" },
  { id: "es", label: "Español", whisper: "spanish" },
  { id: "fr", label: "Français", whisper: "french" },
  { id: "de", label: "Deutsch", whisper: "german" },
  { id: "pt", label: "Português", whisper: "portuguese" },
  { id: "ru", label: "Русский", whisper: "russian" },
  { id: "it", label: "Italiano", whisper: "italian" },
  { id: "vi", label: "Tiếng Việt", whisper: "vietnamese" },
  { id: "th", label: "ไทย", whisper: "thai" },
  { id: "ar", label: "العربية", whisper: "arabic" },
  { id: "hi", label: "हिन्दी", whisper: "hindi" },
  { id: "id", label: "Indonesia", whisper: "indonesian" },
  { id: "tr", label: "Türkçe", whisper: "turkish" },
  { id: "nl", label: "Nederlands", whisper: "dutch" },
  { id: "pl", label: "Polski", whisper: "polish" },
  { id: "uk", label: "Українська", whisper: "ukrainian" },
];

export const LOCAL_MODELS: LocalModel[] = [
  {
    id: "whisper-tiny",
    hf: "Xenova/whisper-tiny",
    name: "Whisper Tiny",
    nameZh: "Whisper Tiny",
    task: "stt",
    sizeLabel: "41 MB",
    quality: "fast",
    langs: "99 languages",
    langsZh: "99 種語言",
    note: "Best starting point for phones.",
  },
  {
    id: "whisper-base",
    hf: "Xenova/whisper-base",
    name: "Whisper Base",
    nameZh: "Whisper Base",
    task: "stt",
    sizeLabel: "77 MB",
    quality: "balanced",
    langs: "99 languages",
    langsZh: "99 種語言",
  },
  {
    id: "whisper-small",
    hf: "Xenova/whisper-small",
    name: "Whisper Small",
    nameZh: "Whisper Small",
    task: "stt",
    sizeLabel: "250 MB",
    quality: "accurate",
    langs: "99 languages",
    langsZh: "99 種語言",
  },
  {
    id: "mt-en-zh",
    hf: "Xenova/opus-mt-en-zh",
    name: "OPUS EN → ZH",
    nameZh: "OPUS 英 → 中",
    task: "mt",
    sizeLabel: "84 MB",
    quality: "balanced",
    langs: "English → Chinese",
    langsZh: "英語 → 中文",
    src: "en",
    tgt: "zh",
  },
  {
    id: "mt-zh-en",
    hf: "Xenova/opus-mt-zh-en",
    name: "OPUS ZH → EN",
    nameZh: "OPUS 中 → 英",
    task: "mt",
    sizeLabel: "84 MB",
    quality: "balanced",
    langs: "Chinese → English",
    langsZh: "中文 → 英語",
    src: "zh",
    tgt: "en",
  },
  {
    id: "mt-en-ja",
    hf: "Xenova/opus-mt-en-jap",
    name: "OPUS EN → JA",
    nameZh: "OPUS 英 → 日",
    task: "mt",
    sizeLabel: "90 MB",
    quality: "balanced",
    langs: "English → Japanese",
    langsZh: "英語 → 日語",
    src: "en",
    tgt: "ja",
  },
  {
    id: "mt-ja-en",
    hf: "Xenova/opus-mt-ja-en",
    name: "OPUS JA → EN",
    nameZh: "OPUS 日 → 英",
    task: "mt",
    sizeLabel: "90 MB",
    quality: "balanced",
    langs: "Japanese → English",
    langsZh: "日語 → 英語",
    src: "ja",
    tgt: "en",
  },
  {
    id: "mt-en-ko",
    hf: "Xenova/opus-mt-en-ko",
    name: "OPUS EN → KO",
    nameZh: "OPUS 英 → 韓",
    task: "mt",
    sizeLabel: "90 MB",
    quality: "balanced",
    langs: "English → Korean",
    langsZh: "英語 → 韓語",
    src: "en",
    tgt: "ko",
  },
  {
    id: "mt-ko-en",
    hf: "Xenova/opus-mt-ko-en",
    name: "OPUS KO → EN",
    nameZh: "OPUS 韓 → 英",
    task: "mt",
    sizeLabel: "90 MB",
    quality: "balanced",
    langs: "Korean → English",
    langsZh: "韓語 → 英語",
    src: "ko",
    tgt: "en",
  },
  {
    id: "mt-en-es",
    hf: "Xenova/opus-mt-en-es",
    name: "OPUS EN → ES",
    nameZh: "OPUS 英 → 西",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "English → Spanish",
    langsZh: "英語 → 西語",
    src: "en",
    tgt: "es",
  },
  {
    id: "mt-es-en",
    hf: "Xenova/opus-mt-es-en",
    name: "OPUS ES → EN",
    nameZh: "OPUS 西 → 英",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "Spanish → English",
    langsZh: "西語 → 英語",
    src: "es",
    tgt: "en",
  },
  {
    id: "mt-en-fr",
    hf: "Xenova/opus-mt-en-fr",
    name: "OPUS EN → FR",
    nameZh: "OPUS 英 → 法",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "English → French",
    langsZh: "英語 → 法語",
    src: "en",
    tgt: "fr",
  },
  {
    id: "mt-fr-en",
    hf: "Xenova/opus-mt-fr-en",
    name: "OPUS FR → EN",
    nameZh: "OPUS 法 → 英",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "French → English",
    langsZh: "法語 → 英語",
    src: "fr",
    tgt: "en",
  },
  {
    id: "mt-en-de",
    hf: "Xenova/opus-mt-en-de",
    name: "OPUS EN → DE",
    nameZh: "OPUS 英 → 德",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "English → German",
    langsZh: "英語 → 德語",
    src: "en",
    tgt: "de",
  },
  {
    id: "mt-de-en",
    hf: "Xenova/opus-mt-de-en",
    name: "OPUS DE → EN",
    nameZh: "OPUS 德 → 英",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "German → English",
    langsZh: "德語 → 英語",
    src: "de",
    tgt: "en",
  },
  {
    id: "mt-en-vi",
    hf: "Xenova/opus-mt-en-vi",
    name: "OPUS EN → VI",
    nameZh: "OPUS 英 → 越",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "English → Vietnamese",
    langsZh: "英語 → 越南語",
    src: "en",
    tgt: "vi",
  },
  {
    id: "mt-vi-en",
    hf: "Xenova/opus-mt-vi-en",
    name: "OPUS VI → EN",
    nameZh: "OPUS 越 → 英",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "Vietnamese → English",
    langsZh: "越南語 → 英語",
    src: "vi",
    tgt: "en",
  },
  {
    id: "mt-en-ru",
    hf: "Xenova/opus-mt-en-ru",
    name: "OPUS EN → RU",
    nameZh: "OPUS 英 → 俄",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "English → Russian",
    langsZh: "英語 → 俄語",
    src: "en",
    tgt: "ru",
  },
  {
    id: "mt-ru-en",
    hf: "Xenova/opus-mt-ru-en",
    name: "OPUS RU → EN",
    nameZh: "OPUS 俄 → 英",
    task: "mt",
    sizeLabel: "80 MB",
    quality: "balanced",
    langs: "Russian → English",
    langsZh: "俄語 → 英語",
    src: "ru",
    tgt: "en",
  },
];

export function findModel(id: string) {
  return LOCAL_MODELS.find((m) => m.id === id);
}

export function findMtModel(src: string, tgt: string) {
  return LOCAL_MODELS.find((m) => m.task === "mt" && m.src === src && m.tgt === tgt);
}

export function langLabel(id: string) {
  return LANGUAGES.find((l) => l.id === id)?.label ?? id;
}
